### ISSUE TITLE
remove_odoo_enterprise version16 BUG

### ISSUE THREAD

**Issue by tanapa2018** [OCA/server-brand#71] opened 2023-03-17 06:34 UTC
## Module
The name of the module that has a bug.
remove_odoo_enterprise
## Describe the bug
Open the settings page from Sales-Settings, and all the functions of the enterprise version will be displayed
## To Reproduce
**Affected versions**:

1.Sales-Settings
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
![1679034759919](https://user-images.githubusercontent.com/44516588/225830231-6a5d080c-ddee-4209-a60b-1fa4550360f7.png)
![1679034779349](https://user-images.githubusercontent.com/44516588/225830274-ea057938-7bcc-41b7-b992-f58e602cb367.png)

**Comment by astirpe** [comment] 2023-03-17 07:14
@tanapa2018 I just tried in runboat and I can't reproduce the bug:

![image](https://user-images.githubusercontent.com/7657635/225837047-1e4a9147-2e32-4a47-8dad-cd2b0646e068.png)

**Comment by pedrobaeza** [comment] 2023-03-17 07:15
There are weird colors, so it can be any theming module that breaks this one. Anyway, it's not a problem of the module, so closing.

**Closed as completed by pedrobaeza** 2023-03-17 07:15 UTC
Labels: bug

**Comment by tanapa2018** [comment] 2023-03-17 07:18
Hello astirpe!
Please test again in python 3.10
Thanks!

**Comment by tanapa2018** [comment] 2023-03-17 07:21
> There are weird colors, so it can be any theming module that breaks this one. Anyway, it's not a problem of the module, so closing.

![1679037549896](https://user-images.githubusercontent.com/44516588/225838819-d9d903fd-80ec-4dcd-a7eb-7c80f865c747.png)

**Comment by tanapa2018** [comment] 2023-03-17 07:22
@pedrobaeza @astirpe

**Comment by pedrobaeza** [comment] 2023-03-17 07:24
This is something of your setup, and Python version has nothing to do with this. It's working on runboat. If you are able to replicate the problem in it, please tell us the steps to do it.

**Comment by astirpe** [comment] 2023-03-17 07:29
I made another test in my laptop, installing module `remove_odoo_enterprise` in combination with module `web_responsive`. It all works fine. I'm sorry @tanapa2018 but it seems something related to your local setup.

**Comment by tanapa2018** [comment] 2023-03-17 07:30
OK, thanks! let me check why

Andrea Stirpe ***@***.***> 于2023年3月17日周五 14:29写道：
